/**
 * Central registry of every error code the API can return.
 * Keeping these in one file prevents typos like "PHONE_ALREADY_REGISTERD"
 * silently breaking frontend error handling.
 */
export enum ErrorCode {
  // ── Generic ──────────────────────────────────────────────────────────────
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  BAD_REQUEST = "BAD_REQUEST",

  // ── Auth: registration ───────────────────────────────────────────────────
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",
  PHONE_CANNOT_BE_VERIFIED = "PHONE_CANNOT_BE_VERIFIED",

  // ── Auth: OTP ────────────────────────────────────────────────────────────
  INVALID_OTP = "INVALID_OTP",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_ATTEMPTS_EXCEEDED = "OTP_ATTEMPTS_EXCEEDED",
  OTP_NOT_REQUESTED = "OTP_NOT_REQUESTED",

  // ── Auth: registration token / pin ──────────────────────────────────────
  REGISTRATION_TOKEN_INVALID = "REGISTRATION_TOKEN_INVALID",
  REGISTRATION_TOKEN_EXPIRED = "REGISTRATION_TOKEN_EXPIRED",
  PHONE_NOT_VERIFIED = "PHONE_NOT_VERIFIED",
  PIN_ALREADY_SET = "PIN_ALREADY_SET",

  // ── Auth: login ──────────────────────────────────────────────────────────
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED",

  // ── Auth: tokens ─────────────────────────────────────────────────────────
  REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REUSE = "REFRESH_TOKEN_REUSE",

  // ── Users — profile ───────────────────────────────────────────────────────
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PROFILE_UPDATE_FAILED = "USER_UPDATE_FAILED",
  INVALID_OLD_PIN = "USER_INVALID_OLD_PIN",
  PIN_CHANGE_SAME = "USER_PIN_SAME_AS_OLD",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",

  // Cloudinary / Photo Upload
  PHOTO_UPLOAD_REQUIRED = "USER_PHOTO_REQUIRED",
  PHOTO_UPLOAD_FAILED = "USER_PHOTO_UPLOAD_FAILED",
  INVALID_IMAGE_FORMAT = "USER_INVALID_IMAGE_FORMAT",

  // ── Users — payment details ───────────────────────────────────────────────
  PAYMENT_DETAILS_NOT_SET = "PAYMENT_DETAILS_NOT_SET",
  PAYMENT_DETAILS_ALREADY_SET = "USER_PAYMENT_DETAILS_EXIST",
  INVALID_MOMO_NUMBER = "USER_INVALID_MOMO_NUMBER",
  PAYSTACK_SUBACCOUNT_FAILED = "USER_PAYSTACK_SUBACCOUNT_CREATION_FAILED",
  UNSUPPORTED_MOBILE_NETWORK = "UNSUPPORTED_MOBILE_NETWORK",
  PAYMENT_DETAILS_ROLE_FORBIDDEN = "PAYMENT_DETAILS_ROLE_FORBIDDEN",

  // ── Agent ─────────────────────────────────────────────────────────────────
  NOT_AN_AGENT = "NOT_AN_AGENT",
  CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND",
  ALREADY_HAS_ACTIVE_AGENT = "ALREADY_HAS_ACTIVE_AGENT",
  CANNOT_ASSIGN_SELF = "CANNOT_ASSIGN_SELF",
  CLIENT_ALREADY_REGISTERED = "CLIENT_ALREADY_REGISTERED",
  CLIENT_NOT_ASSIGNED_TO_AGENT = "AGENT_CLIENT_UNAUTHORIZED_ACCESS",
  UNASSIGN_FAILED = "AGENT_CLIENT_UNASSIGN_FAILED",
  PAYMENT_INITIALIZATION_FAILED = "PAYMENT_INITIALIZATION_FAILED",

  // ── Listings ──────────────────────────────────────────────────────────────
  LISTING_NOT_FOUND = "LISTING_NOT_FOUND",
  LISTING_NOT_AVAILABLE = "LISTING_NOT_AVAILABLE",
  LISTING_HAS_ACTIVE_ORDER = "LISTING_HAS_ACTIVE_ORDER",
  LISTING_FORBIDDEN = "LISTING_FORBIDDEN",
  PACKAGING_NOT_FOUND = "PACKAGING_NOT_FOUND",
  AGENT_CLIENT_FORBIDDEN = "AGENT_CLIENT_FORBIDDEN",
  QUANTITY_EXCEEDS_AVAILABLE = "QUANTITY_EXCEEDS_AVAILABLE",
  HARVEST_DATE_IN_PAST = "HARVEST_DATE_IN_PAST",

  // ── Orders ────────────────────────────────────────────────────────────────
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  ORDER_FORBIDDEN = "ORDER_FORBIDDEN",
  ORDER_NOT_PAID = "ORDER_NOT_PAID",
  ORDER_INVALID_TRANSITION = "ORDER_INVALID_TRANSITION",
  ORDER_ALREADY_CONFIRMED = "ORDER_ALREADY_CONFIRMED",
  ORDER_CANNOT_CANCEL = "ORDER_CANNOT_CANCEL",
  ORDER_DECLINE_REASON_REQUIRED = "ORDER_DECLINE_REASON_REQUIRED",
  LISTING_NOT_ACTIVE_FOR_ORDER = "LISTING_NOT_ACTIVE_FOR_ORDER",
  INBOUND_SMS_INVALID_SIGNATURE = "INBOUND_SMS_INVALID_SIGNATURE",
  INBOUND_SMS_UNKNOWN_COMMAND = "INBOUND_SMS_UNKNOWN_COMMAND",

  // ── Ratings ────────────────────────────────────────────────────────────────
  RATING_ALREADY_EXISTS = "RATING_ALREADY_EXISTS",

  // ── Transport Request ────────────────────────────────────────────────────────────────
  TRANSPORT_ALREADY_EXISTS = "TRANSPORT_ALREADY_EXISTS",
}
